#mongodb container 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset 
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: baragu123/mongo-image:1.0.0
        ports:        
        - containerPort: 27017
          name : mongodb-port

        volumeMounts:
        - name: yolo-volume 
          mountPath: /data/db
    
      volumes: 
      - name : yolo-volume 
        persistentVolumeClaim: 
          claimName: yolo-pvc  