version: '3.8'

services:
  clientapp:
    image: baragu123/client-image:1.4.1
    container_name: client-container
    build:
      context: ./client
    ports:
      - "3000:3000" 
    stdin_open: true
    networks:
      - yolonetwork     

  backendapp:
    image: baragu123/backend-image:1.6.2
    container_name: backend-container
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - yolonetwork
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    # volumes:
    #  - yolovolume
    
  mongodb:
    image: baragu123/mongo-image:1.0.0
    container_name: mongodb
    build: .
    ports: 
      - "27018:27017"
    networks:
      - yolonetwork
    

volumes:
  yolovolume:

networks:
  yolonetwork:
    driver: bridge
