version: '3.8'

services:
  clientapp:
    # image: client-image
    # container_name: client-container
    build:
      context: ./client
    ports:
      - "3000:3000" 
    stdin_open: true
    networks:
      - yolonetwork     

  backendapp:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - yolonetwork
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    # volumes:
    #   - yolovolume
    
  mongodb:
    build: .
    ports: 
      - "27018:27017"
    networks:
      - yolonetwork
    

volumes:
  yolovolume:

networks:
  yolonetwork:
    driver: bridge
