apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    security:
      authorization: "disabled"

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  backend.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 5000
    security:
      authorization: "disabled"