apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017 
      targetPort: 27017 #defined in mongodb statefulset
      #nodePort: 30001 
      name: mongodb-port
