apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1001 # Ensures the volume is accessible by the specified user
      containers:
      - name: mongodb
        image: baragu123/mongo-image:1.0.0
        ports:
        - containerPort: 27017
          name: mongodb-port
        volumeMounts:
        - name: yolo-volume
          mountPath: /data/db

        - name: config-volume
          mountPath: /etc/mongod.conf
          subPath: mongod.conf
        
      volumes:
      - name: config-volume
        configMap:
          name: mongodb-config

        env:
        - name: MONGODB_URI
          value: mongodb://mongodb-service:27017
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
  volumeClaimTemplates:
  - metadata:
      name: yolo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

  