apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: ClusterIP
  selector:
    app: yolo-pods
    component: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb-port
