#mongodb container 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset 
spec:
  selector:
    matchLabels:
      app: mongodb
      component: mongodb
  serviceName: mongodb-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: baragu123/mongo-image:1.0.0
        ports:        
        - containerPort: 27017
          name : mongodb-port

        volumeMounts:
        - name: yolo-volume 
          mountPath: /app
    
    volumes: 
      - name : yolo-volume 
        persistentVolumeClaim: 
          claimName: yolo-pvc
      

  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
    
      
      
      
      

      