#loadbalancer service
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
spec:
  type: LoadBalancer
  selector:
    app: yolo-pods
  ports:
    - port: 3000
      targetPort: 3000
      name: client-port
    - port: 5000
      targetPort: 5000
      name: backend-port
